### ISSUE TITLE
Add github action to run tests

### ISSUE THREAD

**Issue by albe** [sorenmalling/Flowpack.RestApi#6]
The available tests should be run on every PR. Github actions is the way to go IMO.
As a side-effect of this effort, a github action template for any Flow package to run tests could be made available.

**Comment by sorenmalling** [comment]
>  As a side-effect of this effort, a github action template for any Flow package to run tests could be made available.

YES 🤩

I'll talk to Jon and Seb - they did some work with github actions

**Comment by Sebobo** [comment]
Yes you can take a loot at my Media UI actions experiment https://github.com/Flowpack/media-ui/actions

Stuff like linting works fine already. But I have problems with running my e2e tests.

**Comment by albe** [comment]
My main head-wrangling I have is that a flow package action needs to actually check out/install `flow-development-collection`, then require the package of the repository, `composer update` and then run the tests.

**Comment by Sebobo** [comment]
Ah that I did kinda here https://github.com/neos/redirecthandler-databasestorage/blob/master/.github/workflows/tests.yml

**Comment by jonnitto** [comment]
My first workflow is this one:
https://gist.github.com/jonnitto/ceec7ebb55e71349f72b2429043f3fb6
